network:
  version: 2
  ethernets:
    lo:
      addresses:
        - 127.0.0.1/8
    eth0:
      dhcp4: true
      dhcp6: false
      match:
        macaddress: d8:5f:ee:00:01:16
      set-name: eth0
      nameservers:
        addresses:
          - 8.8.8.8
          - 1.1.1.1
