network:
  version: 2
  ethernets:
    lo:
      addresses:
        - 127.0.0.1/8
    eth0:
      dhcp4: false
      dhcp6: false
      addresses:
        - 10.0.2.3/24
        - 43.224.225.110/24
      match:
        macaddress: d8:5f:ee:00:01:16
      set-name: eth0
      routes:
        - to: 0.0.0.0/0
          via: 10.0.2.1
      #        - to: 0.0.0.0/0
      #          via: 43.224.225.2
      nameservers:
        addresses:
          - 8.8.8.8
          - 1.1.1.1
