# Source: https://kubernetes.io/zh-cn/docs/reference/config-api/kubeadm-config.v1beta3/
apiVersion: kubeadm.k8s.io/v1beta3
bootstrapTokens:
  - groups:
      - system:bootstrappers:kubeadm:default-node-token
    token: 9a08jv.c0izixklcxtmnze7
    ttl: 24h0m0s
    usages:
      - signing
      - authentication
kind: InitConfiguration
localAPIEndpoint:
  advertiseAddress: 159.75.231.54
  bindPort: 6443
nodeRegistration:
  criSocket: unix:///var/run/containerd/containerd.sock
  # 设定 "kubeadm init" 和 "kubeadm join" 操作期间的镜像拉取策略。此字段的取值可以是 "Always"、"IfNotPresent" 或 "Never" 之一。若此字段未设置，则 kubeadm 使用 "IfNotPresent" 作为其默认值， 换言之，当镜像在主机上不存在时才执行拉取操作
  imagePullPolicy: IfNotPresent
  name: node1
  taints: null
  #kubeletExtraArgs: map[string]string
  #ignorePreflightErrors: [] #例如：IsPrevilegedUser,Swap。 取值 all 忽略所有检查的错误
---
apiServer:
  # certSANs 为 API 服务器签名证书设置额外的使用者备用名称 （SAN）
  certSANs: [ ]
  timeoutForControlPlane: 4m0s
apiVersion: kubeadm.k8s.io/v1beta3
certificatesDir: /etc/kubernetes/pki
clusterName: kubernetes
controllerManager: { }
etcd:
  local:
    dataDir: /var/lib/etcd
#imageRepository: registry.k8s.io
imageRepository: registry.aliyuncs.com/google_containers
kind: ClusterConfiguration
kubernetesVersion: 1.30.1
networking:
  podSubnet: 10.244.0.0/16
  # Kubernetes 服务所使用的子网。 默认值为 "10.96.0.0/12"。
  serviceSubnet: 10.96.0.0/12
  # Kubernetes 服务所使用的 DNS 域名。 默认值为 "cluster.local"。
  dnsDomain: cluster.local
# 为控制平面设置稳定的 IP 地址或 DNS 名称。它可以是有效的 IP 地址或 RFC-1123 DNS 子域，两者都具有可选的 TCP 端口。
# 如果未指定， controlPlaneEndpoint 则使用 advertiseAddress + bindPort ;如果指定了但没有 controlPlaneEndpoint TCP 端口，则使用 。 bindPort 可能的用途包括：
# 在具有多个控制平面实例的集群中，应将此字段分配为控制平面实例前面的外部负载均衡器的地址。
# 在强制节点回收的环境中， controlPlaneEndpoint 可用于为控制平面分配稳定的 DNS
controlPlaneEndpoint: 159.75.231.54:6443

